version: "3"
volumes:
    kong_data: {}
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: kong-25-postgres
    networks:
      - kong-ee
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: kong
    ports:
      - "5432:5432/tcp"
#Running the migrations here
  kong-migrations:
    image: docker.io/kong/kong-gateway:2.5.0.0
    container_name: kong-25-migrations
    command: kong migrations bootstrap
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: postgres
      KONG_PASSWORD: admin
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-25-postgres
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_LICENSE_DATA: '{"license":{"signature":"168aa7565666b8605f944a54a5c83ba9616a80c54ba491b1a007bebb5a4378b1a298b32700369d22909b3eefe0312f779854a27e5e6162b20ddb8fc965ab6fd7","payload":{"customer":"AlecDan","license_creation_date":"2019-03-29","product_subscription":"Kong Enterprise Edition","admin_seats":"5","support_plan":"Business","license_expiration_date":"2030-01-01","license_key":"ASDASDASDASDASDASDASDASDASD_a1VASASD"},"version":1}}'
    links:
      - postgres:postgres
    networks:
      - kong-ee
    restart: on-failure
  kong-ee:
    image: docker.io/kong/kong-gateway:2.5.0.0
    user: "root"
    container_name: kong-25
    networks:
      - kong-ee
    depends_on:
      - postgres
      - kong-migrations
    restart: on-failure
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8003:8003/tcp"
      - "8004:8004/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
      - "8445:8445/tcp"
      - "8446:8446/tcp"
      - "8447:8447/tcp"
      - "9080:9080/tcp"
    environment:
      KONG_ADMIN_GUI_LISTEN:  0.0.0.0:8002, 0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_LICENSE_DATA: '{"license":{"signature":"168aa7565666b8605f944a54a5c83ba9616a80c54ba491b1a007bebb5a4378b1a298b32700369d22909b3eefe0312f779854a27e5e6162b20ddb8fc965ab6fd7","payload":{"customer":"RobCo","license_creation_date":"2019-03-29","product_subscription":"Kong Enterprise Edition","admin_seats":"5","support_plan":"Business","license_expiration_date":"2030-01-01","license_key":"ASDASDASDASDASDASDASDASDASD_a1VASASD"},"version":1}}'
      KONG_LOG_LEVEL: debug
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PORTAL_API_ACCESS_LOG: /dev/stderr
      KONG_PORTAL_API_ERROR_LOG: /dev/stderr
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-25-postgres
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
      KONG_PROXY_ACCESS_LOG: "off"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_PLUGINS: bundled
      KONG_PASSWORD: admin
      KONG_ENFORCE_RBAC: "on"
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_SESSION_CONF: '{"cookie_name":"admin_session","cookie_samesite":"off","secret":"Y29vbGJlYW5z","cookie_secure":false,"storage":"kong"}'
      KONG_PORTAL_EMAILS_FROM: noreply@konghq.com
      KONG_PORTAL_EMAILS_REPLY_TO: noreply@konghq.com
      KONG_PORTAL_GUI_LISTEN: 0.0.0.0:8003
      KONG_PORTAL_GUI_HOST: localhost:8003
      KONG_PORTAL_GUI_PROTOCOL: http
      KONG_PORTAL_GUI_AUTH: baisc-auth
      KONG_SMTP_MOCK: "off"
      KONG_SMTP_HOST: smtp.gmail.com
      KONG_SMTP_PORT: 587
      KONG_SMTP_AUTH_TYPE: plain
      KONG_SMTP_STARTTLS: "on"
      KONG_SMTP_USERNAME: kongemailtest@gmail.com
      KONG_SMTP_PASSWORD: jNzjktjjzhzwYiQdpd2jymXV
      KONG_SMTP_ADMIN_EMAILS: noreply@konghq.com
      KONG_PORTAL_SESSION_CONF: '{ "cookie_name": "portal_session", "secret": "Y29vbGJlYW5z", "storage": "kong", "cookie_secure": false }'
      KONG_ANONYMOUS_REPORTS: "off" 
      KONG_PORTAL: "on"
      KONG_VITALS: "on"
networks:
  kong-ee:
