apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: kong-basic-auth
  annotations:
    kubernetes.io/ingress.class: kong
config: 
  hide_credentials: true
plugin: basic-auth