image:
  repository: kong-docker-kong-enterprise-edition-docker.bintray.io/kong-enterprise-edition
  tag: 2.3.2.0-alpine
  pullSecrets:
    - kong-enterprise-edition-docker

env:
  admin_gui_listen: 0.0.0.0:8002, 0.0.0.0:8445 ssl
  admin_listen: 0.0.0.0:8001, 0.0.0.0:8444 ssl
  database: postgres
  log_level: debug
  audit_log: on
  admin_gui_auth_conf_secret: kong-session-config

  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password
  kong_admin_token:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password
  # admin_gui_session_conf:
  #     valueFrom:
  #     secretKeyRef:
  #       name: kong-session-config
  #       key: admin_gui_session_conf

admin:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:
    # Enable plaintext HTTP listen for the admin API
    # Disabling this and using a TLS listen only is recommended for most configuration
    enabled: true
    servicePort: 8001
    containerPort: 8001
    # Set a nodePort which is available if service type is NodePort
    # nodePort: 32080
    # Additional listen parameters, e.g. "reuseport", "backlog=16384"
    parameters:
    - http

  tls:
    enabled: true
    servicePort: 8444
    containerPort: 8444
    parameters:
    - http2

  # ingress:
  #   enabled: true
  #   tls: kong
  #   hostname: admin.kong.dascole.com
  #   annotations:
  #     kubernetes.io/ingress.class: "kong"
  #   path: /

proxy:
  enabled: true
  type: LoadBalancer
  annotations: {}

  http:
    enabled: true
    servicePort: 9999
    containerPort: 8000
    parameters: []

  tls:
    enabled: true
    servicePort: 9943
    containerPort: 8443
    parameters:
    - http2

  stream: {}

  # ingress:
  #   enabled: true
  #   hosts: []
  #   annotations:
  #     plugins.konghq.com: rl-by-ip
  #   path: /

  externalIPs: []
# Enable/disable migration jobs, and set annotations for them
migrations:
  # Enable pre-upgrade migrations (run "kong migrations up")
  preUpgrade: true
  # Enable post-upgrade migrations (run "kong migrations finish")
  postUpgrade: true
  # Annotations to apply to migrations jobs
  # By default, these disable service mesh sidecar injection for Istio and Kuma,
  # as the sidecar containers do not terminate and prevent the jobs from completing
  annotations:
    sidecar.istio.io/inject: false
    kuma.io/sidecar-injection: "disabled"

# Custom Kong plugins can be loaded into Kong by mounting the plugin code
# into the file-system of Kong container.
# The plugin code should be present in ConfigMap or Secret inside the same
# namespace as Kong is being installed.
# The `name` property refers to the name of the ConfigMap or Secret
# itself, while the pluginName refers to the name of the plugin as it appears
# in Kong.
# Subdirectories (which are optional) require separate ConfigMaps/Secrets.
# "path" indicates their directory under the main plugin directory: the example
# below will mount the contents of kong-plugin-rewriter-migrations at "/opt/kong/rewriter/migrations".
plugins: {}
  # configMaps:
  # - pluginName: rewriter
  #   name: kong-plugin-rewriter
  #   subdirectories:
  #   - name: kong-plugin-rewriter-migrations
  #     path: migrations
  # secrets:
  # - pluginName: rewriter
  #   name: kong-plugin-rewriter
# Inject specified secrets as a volume in Kong Container at path /etc/secrets/{secret-name}/
# This can be used to override default SSL certificates.
# Be aware that the secret name will be used verbatim, and that certain types
# of punctuation (e.g. `.`) can cause issues.
# Example configuration
# secretVolumes:
# - kong-proxy-tls
# - kong-admin-tls
# secretVolumes:
#   - kong-mngr-tls
#   - kong-proxy-tls
#   - kong-admin-tls

enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  vitals:
    enabled: false
  portal:
    enabled: true
  rbac:
    enabled: true
    admin_gui_auth: basic-auth
    admin_gui_auth_conf_secret: kong-session-config

manager:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8002
    containerPort: 8002

  tls:
    enabled: true
    servicePort: 8445
    containerPort: 8445
    parameters:
    - http2
    - https

  # ingress:
  #   enabled: true
  #   tls: kong
  #   hostname: manager.kong.daniello.com
  #   annotations: {}
  #   path: /

  externalIPs: []

portal:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:
    enabled: true
    servicePort: 8003
    containerPort: 8003
    parameters: []

  tls:
    enabled: true
    servicePort: 8446
    containerPort: 8446
    parameters:
    - http2

  externalIPs: []

portalapi:
  enabled: true
  type: LoadBalancer
  annotations:
    konghq.com/protocol: "https"

  http:

  http:
    enabled: true
    servicePort: 8004
    containerPort: 8004
    parameters: []

  tls:
    enabled: true
    servicePort: 8447
    containerPort: 8447
    parameters:
    - http2

  externalIPs: []

postgresql:
  enabled: true
  postgresqlUsername: kong
  postgresqlPassword: kong
  postgresqlDatabase: kong
  service:
    port: 5432

ingressController:
  enabled: true
  installCRDs: false
  env:
    kong_admin_token:
      valueFrom:
        secretKeyRef:
          name: kong-enterprise-superuser-password
          key: password
